# Hardware specification
n_threads: 6    # number of threads for data loading
n_GPUs: 1   # number of GPUs
seed: 6   # random seed

# Data specifications
data_dir: "/home/"    # Datasets root directory

data_name: "IXI"    # Data name: IXI, fastMRI
modal: "PD"   # "the modal of data"
slice_indexes: # slice indexes
  - 40
  - 50
  - 60
  - 70
  - 75
  - 80
  - 85
  - 90
  - 100
  - 110

  # Model specifications
root_path: "/home/"   # root path


n_blocks: 2   # the number of blocks

# Training specifications
save_dir: "experiment"  # directory to save results

  # Optimization specifications
## 学习率的设置和衰减方式
lr: 1e-4    # learning rate
lr_policy: "step"   # learning rate decay mode:steplr/multisteplr/lambdalr
gamma: 0.5    # learning rate decay factor
step_size: 10   # StepLR parameter
multistep_size: 15    # MultiStepLR parameter
epoch_decay: 20   # lambda parameter, the number of iterations that begin to decay

## 优化器的选择
optimizer: "Adam"   # optimizer to use (SGD | Adam | RMSprop)
momentum: 0.9   # SGD momentum
weight_decay: 0   # weight decay (L2 penalty)

# T2Net


